import React from 'react';
export const HomeIcon = (props: any) => <svg {...props}><circle cx="9" cy="9" r="8" fill="currentColor"/></svg>;
export const PetIcon = HomeIcon;
export const ScreenIcon = HomeIcon;
export const MonitorIcon = HomeIcon;
export const WorkspaceIcon = HomeIcon;
export const WindowIcon = HomeIcon;
export const CompositorIcon = HomeIcon;
export const WaybarIcon = HomeIcon;
export const CharacterIcon = HomeIcon;
export const AnimationIcon = HomeIcon;
export const StyleIcon = HomeIcon;
export const MusicIcon = HomeIcon;
export const NotificationIcon = HomeIcon;
export const BrowserIcon = HomeIcon;
export const IntegrationIcon = HomeIcon;
export const CliIcon = HomeIcon;
export const DiagnosticIcon = HomeIcon;
export const SettingsIcon = HomeIcon;
export const SearchIcon = HomeIcon;
